dijkstra:
	g++ -std=c++23 ./dijkstra/main.cpp -o ../../build/dijkstra
floyd-warshall:
	g++ -std=c++23 ./floyd-warshall/main.cpp -o ../../build/floyd-warshall
strongly-connected-components:
	g++ -std=c++23 ./strongly-connected-components/main.cpp -o ../../build/strongly-connected-components
topological-sort:
	g++ -std=c++23 ./topological-sort/main.cpp -o ../../build/topological-sort

clean:
	rm -rf ../../build/*