# Topological sort
topological-sort:
	g++ -std=c++23 ./topological-sort/main.cpp -o ../../build/topological-sort

# Strongly connected components
strongly-connected-components:
	g++ -std=c++23 ./strongly-connected-components/main.cpp -o ../../build/strongly-connected-components

# Shortest paths algorithms
dijkstra: # add optimised version
	g++ -std=c++23 ./dijkstra/main.cpp -o ../../build/dijkstra

floyd-warshall:
	g++ -std=c++23 ./floyd-warshall/main.cpp -o ../../build/floyd-warshall

bellman-ford: # add optimised version
	g++ -std=c++23 ./bellman-ford/main.cpp -o ../../build/bellman-ford

# Disjoint-set data structure
disjoint-set-union:
	g++ -std=c++23 ./disjoint-set-union/main.cpp -o ../../build/disjoint-set-union

# Utilities
clean:
	rm -rf ../../build/*