# Topological sort
topological-sort:
	g++ -std=c++23 ./topological-sort/main.cpp -o ../../build/topological-sort

# Strongly connected components
strongly-connected-components:
	g++ -std=c++23 ./strongly-connected-components/main.cpp -o ../../build/strongly-connected-components

# Shortest paths algorithms
dijkstra: # add optimised version
	g++ -std=c++23 ./dijkstra/main.cpp -o ../../build/dijkstra

floyd-warshall:
	g++ -std=c++23 ./floyd-warshall/main.cpp -o ../../build/floyd-warshall

bellman-ford: # add optimised version
	g++ -std=c++23 ./bellman-ford/main.cpp -o ../../build/bellman-ford

directed-acyclic-graph:
	g++ -std=c++23 ./directed-acyclic-graph/main.cpp -o ../../build/directed-acyclic-graph

# Disjoint-set data structure
disjoint-set-union:
	g++ -std=c++23 ./disjoint-set-union/main.cpp -o ../../build/disjoint-set-union

# Minimum spanning tree
kruskal:
	g++ -std=c++23 ./kruskal/main.cpp -o ../../build/kruskal

prim:
	g++ -std=c++23 ./prim/main.cpp -o ../../build/prim

# Maximum flows
ford-fulkerson:
	g++ -std=c++23 ./ford-fulkerson/main.cpp -o ../../build/ford-fulkerson

edmonds-karp:
	g++ -std=c++23 ./edmonds-karp/main.cpp -o ../../build/edmonds-karp

# Utilities
clean:
	rm -rf ../../build/*