# AF 2
af-2-1:
	g++ -std=c++23 ./af-2/1.cpp -o ../../build/1

af-2-2:
	g++ -std=c++23 ./af-2/2.cpp -o ../../build/2

af-2-3:
	g++ -std=c++23 ./af-2/3.cpp -o ../../build/3


# Utilities
clean:
	rm -rf ../../build/*