# AF 2
af-2-1:
	g++ -std=c++23 ./af-2/1.cpp -o ../../build/1

af-2-2:
	g++ -std=c++23 ./af-2/2.cpp -o ../../build/2

af-2-3:
	g++ -std=c++23 ./af-2/3.cpp -o ../../build/3

# Restanta AF 1
r-af-1-1:
	g++ -std=c++23 ./r-af-1/1.cpp -o ../../build/1

r-af-1-2:
	g++ -std=c++23 ./r-af-1/2.cpp -o ../../build/2

r-af-1-3:
	g++ -std=c++23 ./r-af-1/3.cpp -o ../../build/3

# Restanta AF Toamna
r-af-t-1:
	g++ -std=c++23 ./r-af-t/1.cpp -o ../../build/1

r-af-t-2:
	g++ -std=c++23 ./r-af-t/2.cpp -o ../../build/2

r-af-t-3:
	g++ -std=c++23 ./r-af-t/3.cpp -o ../../build/3

# Utilities
clean:
	rm -rf ../../build/*